# apiVersion: v1
# kind: Namespace
# metadata:
#   name: flowtrove
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace
  namespace: flowtrove
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workspace
  template:
    metadata:
      labels:
        app: workspace
    spec:
      imagePullSecrets:
        - name: registry-01-secret
      containers:
      - name: workspace
        image: registry-01.flowtrove.com/flowtrove/workspace:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: ENV
            value: "production"
          - name: AUTH_URL
            value: "https://www.flowtrove.com"
          - name: PORT
            value: "3000"
          - name: ADDRESS
            value: "0.0.0.0"
          - name: JWT_SECRET
            value: "tgregftrjcfidughvtriufghenfitvurjngiufvnctriejgnwsfiurjkndrydsgafucrebusdfhwcje"
          - name: DATABASE_URL
            value: "postgres://imolla:gdfsvfdsvfeds8e7y87dy8h8@10.100.100.200:5432/flowtrove_dev"      
          - name: MAIL_URL
            value: smtp://support%40flowtrove.com:Skrapari2252!@smtp.hostinger.com:587      

---
apiVersion: v1
kind: Service
metadata:
  name: workspace
  namespace: flowtrove
spec:
  selector:
    app: workspace
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP