package students

// mockFilterItems powers multi-select column options (study_level, faculties, etc.).
var mockFilterItems = []map[string]any{
	{"id": "i-bachelor", "name": "Bachelor", "reference": "study_level"},
	{"id": "i-master", "name": "Master", "reference": "study_level"},
	{"id": "i-doctorate", "name": "Doktoraturë", "reference": "study_level"},
	{"id": "f-economy", "name": "Fakulteti i Ekonomisë", "reference": "faculties"},
	{"id": "f-law", "name": "Fakulteti i Drejtësisë", "reference": "faculties"},
	{"id": "f-engineering", "name": "Fakulteti i Inxhinierisë", "reference": "faculties"},
	{"id": "sp-finance", "name": "Financë", "reference": "study_program"},
	{"id": "sp-marketing", "name": "Marketing", "reference": "study_program"},
	{"id": "sp-civil", "name": "Inxhinieri Civile", "reference": "study_program"},
	{"id": "prof-general", "name": "Profil i Përgjithshëm", "reference": "study_profile"},
	{"id": "prof-applied", "name": "Profil i Aplikuar", "reference": "study_profile"},
}

var mockTemplates = []map[string]any{
	{"id": "tpl-1", "name": "Suplement Bachelor"},
	{"id": "tpl-2", "name": "Suplement Master"},
	{"id": "tpl-3", "name": "Suplement i Diplomës"},
}

func mockStudentsData() []map[string]any {
	return []map[string]any{
		{
			"id":                  "stu-001",
			"first_name":          "Arben",
			"last_name":           "Krasniqi",
			"full_name":           "Arben Krasniqi",
			"email":               "arben.krasniqi@student.uet.edu.al",
			"student_code":        "UET2021001",
			"image":               "",
			"study_level":         "bachelor",
			"status":              "Aktiv",
			"faculty_name":        "Fakulteti i Ekonomisë",
			"faculty_code":        "FE",
			"faculty_id":          "f-economy",
			"study_program_name":  "Financë",
			"study_program_code":  "FIN",
			"study_program_id":    "sp-finance",
			"study_profile_name":  "Profil i Përgjithshëm",
			"study_profile_id":    "prof-general",
			"graduated_at":        "2024-06-15",
			"created_at":          "2021-10-01T08:00:00Z",
		},
		{
			"id":                  "stu-002",
			"first_name":          "Elira",
			"last_name":           "Hoxha",
			"full_name":           "Elira Hoxha",
			"email":               "elira.hoxha@student.uet.edu.al",
			"student_code":        "UET2020042",
			"image":               "",
			"study_level":         "master",
			"status":              "Aktiv",
			"faculty_name":        "Fakulteti i Drejtësisë",
			"faculty_code":        "FD",
			"faculty_id":          "f-law",
			"study_program_name":  "Marketing",
			"study_program_code":  "MKT",
			"study_program_id":    "sp-marketing",
			"study_profile_name":  "Profil i Aplikuar",
			"study_profile_id":    "prof-applied",
			"graduated_at":        "2025-01-20",
			"created_at":          "2020-09-15T08:00:00Z",
		},
		{
			"id":                  "stu-003",
			"first_name":          "Besnik",
			"last_name":           "Berisha",
			"full_name":           "Besnik Berisha",
			"email":               "besnik.berisha@student.uet.edu.al",
			"student_code":        "UET2019088",
			"image":               "",
			"study_level":         "bachelor",
			"status":              "Diplomuar",
			"faculty_name":        "Fakulteti i Inxhinierisë",
			"faculty_code":        "FI",
			"faculty_id":          "f-engineering",
			"study_program_name":  "Inxhinieri Civile",
			"study_program_code":  "IC",
			"study_program_id":    "sp-civil",
			"study_profile_name":  "Profil i Përgjithshëm",
			"study_profile_id":    "prof-general",
			"graduated_at":        "2023-07-10",
			"created_at":          "2019-10-01T08:00:00Z",
		},
		{
			"id":                  "stu-004",
			"first_name":          "Drita",
			"last_name":           "Gashi",
			"full_name":           "Drita Gashi",
			"email":               "drita.gashi@student.uet.edu.al",
			"student_code":        "UET2022015",
			"image":               "",
			"study_level":         "master",
			"status":              "Aktiv",
			"faculty_name":        "Fakulteti i Ekonomisë",
			"faculty_code":        "FE",
			"faculty_id":          "f-economy",
			"study_program_name":  "Financë",
			"study_program_code":  "FIN",
			"study_program_id":    "sp-finance",
			"study_profile_name":  "Profil i Aplikuar",
			"study_profile_id":    "prof-applied",
			"graduated_at":        "",
			"created_at":          "2022-10-01T08:00:00Z",
		},
		{
			"id":                  "stu-005",
			"first_name":          "Erion",
			"last_name":           "Malaj",
			"full_name":           "Erion Malaj",
			"email":               "erion.malaj@student.uet.edu.al",
			"student_code":        "UET2017055",
			"image":               "",
			"study_level":         "doctorate",
			"status":              "Aktiv",
			"faculty_name":        "Fakulteti i Inxhinierisë",
			"faculty_code":        "FI",
			"faculty_id":          "f-engineering",
			"study_program_name":  "Inxhinieri Civile",
			"study_program_code":  "IC",
			"study_program_id":    "sp-civil",
			"study_profile_name":  "Profil i Aplikuar",
			"study_profile_id":    "prof-applied",
			"graduated_at":        "2022-12-01",
			"created_at":          "2017-10-01T08:00:00Z",
		},
		{
			"id":                  "stu-006",
			"first_name":          "Fjolla",
			"last_name":           "Ahmeti",
			"full_name":           "Fjolla Ahmeti",
			"email":               "fjolla.ahmeti@student.uet.edu.al",
			"student_code":        "UET2021033",
			"image":               "",
			"study_level":         "bachelor",
			"status":              "Jo aktiv",
			"faculty_name":        "Fakulteti i Drejtësisë",
			"faculty_code":        "FD",
			"faculty_id":          "f-law",
			"study_program_name":  "Marketing",
			"study_program_code":  "MKT",
			"study_program_id":    "sp-marketing",
			"study_profile_name":  "Profil i Përgjithshëm",
			"study_profile_id":    "prof-general",
			"graduated_at":        "",
			"created_at":          "2021-10-01T08:00:00Z",
		},
		{
			"id":                  "stu-007",
			"first_name":          "Gent",
			"last_name":           "Leka",
			"full_name":           "Gent Leka",
			"email":               "gent.leka@student.uet.edu.al",
			"student_code":        "UET2020067",
			"image":               "",
			"study_level":         "bachelor",
			"status":              "Diplomuar",
			"faculty_name":        "Fakulteti i Ekonomisë",
			"faculty_code":        "FE",
			"faculty_id":          "f-economy",
			"study_program_name":  "Marketing",
			"study_program_code":  "MKT",
			"study_program_id":    "sp-marketing",
			"study_profile_name":  "Profil i Përgjithshëm",
			"study_profile_id":    "prof-general",
			"graduated_at":        "2024-07-22",
			"created_at":          "2020-10-01T08:00:00Z",
		},
		{
			"id":                  "stu-008",
			"first_name":          "Hana",
			"last_name":           "Shehu",
			"full_name":           "Hana Shehu",
			"email":               "hana.shehu@student.uet.edu.al",
			"student_code":        "UET2023012",
			"image":               "",
			"study_level":         "master",
			"status":              "Aktiv",
			"faculty_name":        "Fakulteti i Drejtësisë",
			"faculty_code":        "FD",
			"faculty_id":          "f-law",
			"study_program_name":  "Financë",
			"study_program_code":  "FIN",
			"study_program_id":    "sp-finance",
			"study_profile_name":  "Profil i Aplikuar",
			"study_profile_id":    "prof-applied",
			"graduated_at":        "",
			"created_at":          "2023-10-01T08:00:00Z",
		},
	}
}

func mockFilterItemsData() []any {
	items := make([]any, len(mockFilterItems))
	for i, item := range mockFilterItems {
		items[i] = item
	}
	return items
}

func mockTemplatesData() []any {
	items := make([]any, len(mockTemplates))
	for i, item := range mockTemplates {
		items[i] = item
	}
	return items
}
