# apiVersion: v1
# kind: Namespace
# metadata:
#   name: uetedu-v3
#   labels:
#     pod-security.kubernetes.io/enforce: privileged
#     pod-security.kubernetes.io/warn: privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: uetedu-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-worker2
      containers:
        - name: postgres-db
          image: postgres:18.4
          # image: postgres:17.6
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: imolla
            - name: POSTGRES_DB
              value: uetapp
            - name: POSTGRES_PASSWORD
              value: "fgvgyfdtgxfchgfxtrfdcgvgffgcvjfgchgfc"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
      volumes:
        - name: data
          nfs:
            server: 192.168.5.151
            path: /mnt/databases/postgres-db
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: uetedu-v3
spec:
  type: ClusterIP
  clusterIP: 10.100.2.200
  selector:
    app: postgres-db
  ports:
    - name: postgres-db
      protocol: TCP
      port: 5432
      targetPort: 5432